# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e49c1bd941089bde1470e8f1ff21e6b8375c698780d586f9e4d7feee23c6185a3e11d977e12f2ca7b09da7a72769344a55d66a7e1cbc56e0625a8a458b788a4

test:
  secret_key_base: b19fc0b1849deda692bd4298befc4a5a6e6cb952e882384ba6b05822e7d908baef1f53fbff82b86e2ac6a19d25fda19087227367d855d9f6f93a1a76ffeab475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
